[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PROTEUS"
version = "v1.0.0"
description = "Proteus is a configurable tool for editing structured documents, based on the concept of archetypes."
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "lxml>=6.1.0",
    "pyqt6-qt6==6.11.0",
    "pyqt6==6.11.0",
    "shortuuid==1.0.13",
    "strenum==0.4.15",
    "typing-extensions==4.15.0",
    "pyqt6-sip==13.11.1",
    "pyqt6-webengine==6.11.0",
    "pyqt6-webengine-qt6==6.11.0",
    "pyyaml==6.0.3",
    "markdown>=3.8.1",
    "pyspellchecker==0.9.0",
    "trieregex==1.0.0",
]

[dependency-groups]
dev = [
    "mypy==1.20.2",
    "mypy-extensions==1.1.0",
    "pytest>=9.0.3",
    "pytest-mock==3.15.1",
    "pytest-lazy-fixtures==1.4.0",
    "pytest-qt==4.5.0",
    "pytest-xvfb==3.1.1",
    "pytest-order==1.4.0",
    "coverage==7.13.5",
    "pytest-cov==7.1.0",
    "pyinstaller==6.20.0",
]

[project.scripts]
proteus = "proteus.__main__:main"
