<?xml version="1.0" encoding="utf-8"?>

<!-- ======================================================== -->
<!-- File    : document.xsl                                   -->
<!-- Content : PROTEUS LaTeX XSLT for documents               -->
<!-- Author  : Amador Durán Toro                              -->
<!-- Date    : 2026/10/07                                     -->
<!-- Version : 1.0                                            -->
<!-- ======================================================== -->

<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:proteus="http://proteus.us.es"
    xmlns:proteus-utils="http://proteus.us.es/utils"
    exclude-result-prefixes="proteus proteus-utils"
>
  <!-- Match the root object of the document -->
  <xsl:template match="object[@classes=':Proteus-document']">

    <!-- Preamble: the language comes from the profile i18n files.    -->
    <!-- twoside: chapters of the document (cover, table of contents, -->
    <!-- body) start on odd pages, see \cleardoublepage below.        -->
    <xsl:text>% Generated by PROTEUS&#10;</xsl:text>
    <xsl:text>\documentclass[12pt,a4paper,twoside,titlepage]{article}&#10;</xsl:text>
    <xsl:text>\usepackage[</xsl:text>
    <xsl:value-of select="proteus-utils:i18n('xslt.latex_babel_language')"/>
    <xsl:text>]{babel}&#10;</xsl:text>
    <xsl:text>\usepackage{resources/proteus}&#10;</xsl:text>

    <!-- Text shown instead of a remote figure that could not be downloaded -->
    <xsl:text>\renewcommand{\ProteusMissingImageText}{</xsl:text>
    <xsl:call-template name="label"><xsl:with-param name="key" select="'xslt.remote_figure_not_available'"/></xsl:call-template>
    <xsl:text>}&#10;&#10;</xsl:text>

    <xsl:text>\hypersetup{pdftitle={</xsl:text>
    <xsl:call-template name="tex"><xsl:with-param name="text" select="properties/*[@name=':Proteus-name']"/></xsl:call-template>
    <xsl:text>}, pdfcreator={PROTEUS}}&#10;&#10;</xsl:text>

    <xsl:text>\begin{document}&#10;&#10;</xsl:text>

    <!-- Cover -->
    <xsl:call-template name="document_cover"/>

    <!-- Table of contents -->
    <xsl:text>\renewcommand{\contentsname}{</xsl:text>
    <xsl:call-template name="label"><xsl:with-param name="key" select="'xslt.toc'"/></xsl:call-template>
    <xsl:text>}&#10;\cleardoublepage&#10;\tableofcontents&#10;\cleardoublepage&#10;</xsl:text>

    <!-- Document body -->
    <xsl:apply-templates select="children/object"/>

    <xsl:text>&#10;\end{document}&#10;</xsl:text>
  </xsl:template>

</xsl:stylesheet>
