# ==========================================================================
# File: test_export_latex.py
# Description: pytest file for the LaTeX export strategies of the basic
#              plugin ('latex' and 'pdf_latex'), run with the real
#              controller and the LaTeX template of the basic profile.
# Date: 07/10/2026
# Version: 0.1
# Author: Amador Durán Toro
# ==========================================================================

# --------------------------------------------------------------------------
# Standard library imports
# --------------------------------------------------------------------------

from pathlib import Path

# --------------------------------------------------------------------------
# Third party imports
# --------------------------------------------------------------------------

import pytest
from pytestqt.qtbot import QtBot

# --------------------------------------------------------------------------
# Project specific imports
# --------------------------------------------------------------------------

from proteus.application.resources.plugins import Plugins
from proteus.application.state.manager import StateManager
from proteus.views.components.main_window import MainWindow
from proteus.tests.end2end.fixtures import app, load_project

# --------------------------------------------------------------------------
# Constants
# --------------------------------------------------------------------------

TEST_PROJECT_NAME = "example_project"
TEST_DOCUMENT_ID = "SS2yr44xAPqq"

# The first compilation may be slow (e.g. MiKTeX installing packages)
PDF_EXPORT_TIMEOUT_MS = 300_000


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------


def create_strategy(main_window: MainWindow, name: str):
    """
    Loads the example project, selects a document and creates the export
    strategy registered with the given name, with its form widget.
    """
    load_project(main_window=main_window, project_name=TEST_PROJECT_NAME)
    StateManager().set_current_document(TEST_DOCUMENT_ID)

    # XSLT functions are added to the render service by app.py at start-up
    main_window._controller._render_service.add_functions_to_namespace(
        Plugins().get_xslt_functions()
    )

    strategy_class = Plugins().get_export_strategies()[name]
    strategy = strategy_class(main_window._controller)
    strategy.exportFormWidget()
    return strategy


# --------------------------------------------------------------------------
# End to end LaTeX export tests
# --------------------------------------------------------------------------


def test_export_latex_sources(app, qtbot: QtBot, tmp_path: Path):
    """
    The 'latex' strategy writes main.tex, the template resources (without
    XSLT files), the profile icons and the referenced assets.
    """
    # Arrange ----------------------------------------------------------
    strategy = create_strategy(app, "latex")
    strategy._path_input.setDirectory(tmp_path.as_posix())
    strategy._folder_name_input.setText("exported-latex")

    # Act --------------------------------------------------------------
    with qtbot.waitSignal(strategy.exportFinishedSignal, timeout=30_000) as blocker:
        strategy.export()

    # Assert -----------------------------------------------------------
    path, success = blocker.args
    folder = tmp_path / "exported-latex"

    assert success, f"LaTeX export failed: {path}"
    assert Path(path) == folder

    tex = (folder / "main.tex").read_text(encoding="utf-8")
    assert tex.startswith("% Generated by PROTEUS")
    assert "\\begin{document}" in tex and tex.rstrip().endswith("\\end{document}")
    # The test project has archetypes that are not in the basic profile, so
    # only the template's own labels are checked
    assert "!xslt." not in tex, "Missing translations of the LaTeX template"

    assert (folder / "resources" / "proteus.sty").exists()
    assert (folder / "resources" / "images" / "logo_us.png").exists()
    assert any((folder / "icons").glob("*.png")), "Profile icons must be copied"
    assert not list(folder.rglob("*.xsl")), "XSLT files must not be exported"


def test_export_latex_not_a_view(app):
    """
    LaTeX templates are not offered as views.
    """
    controller = app._controller

    assert "latex" not in controller.get_available_xslt()
    assert [t.name for t in controller.get_templates_by_output_format("latex")] == ["latex"]


def test_export_pdf_latex(app, qtbot: QtBot, tmp_path: Path):
    """
    The 'pdf_latex' strategy compiles the LaTeX sources with an installed
    engine and writes the PDF. Skipped if there is no LaTeX engine.
    """
    # Arrange ----------------------------------------------------------
    strategy = create_strategy(app, "pdf_latex")
    if strategy._engine_selector.count() == 0:
        pytest.skip("No LaTeX engine installed")

    pdf_file = tmp_path / "document.pdf"
    strategy._input.setText(pdf_file.as_posix())

    # Act --------------------------------------------------------------
    with qtbot.waitSignal(
        strategy.exportFinishedSignal, timeout=PDF_EXPORT_TIMEOUT_MS
    ) as blocker:
        strategy.export()

    # Assert -----------------------------------------------------------
    path, success = blocker.args

    assert success, f"PDF export failed, see {pdf_file.with_suffix('.log')}"
    assert Path(path) == pdf_file
    assert pdf_file.read_bytes().startswith(b"%PDF")
