<?xml version="1.0" encoding="utf-8"?>

<!-- ================================================================== -->
<!-- File    : section.xsl                                              -->
<!-- Content : PROTEUS LaTeX XSLT for section                           -->
<!-- Author  : Amador Durán Toro                                        -->
<!-- Date    : 2026/10/07                                               -->
<!-- Version : 1.0                                                      -->
<!-- ================================================================== -->

<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:proteus="http://proteus.us.es"
  xmlns:proteus-utils="http://proteus.us.es/utils"
>
  <!-- ================================================================ -->
  <!-- NOTE #1
       Match expressions and priorities follow the same rules as in the
       default template (see default/archetypes/general/section.xsl).

       NOTE #2
       Unlike the HTML template, section numbers and the table of
       contents are generated by LaTeX: the nesting level is only used
       to choose the sectioning command.
  -->
  <!-- ================================================================ -->

  <xsl:template
    match="object[contains(concat(' ', normalize-space(@classes), ' '),' section ')]"
    name="section_template"
    priority="1"
  >
    <!-- Nesting level -->
    <xsl:param name="nesting_level" select="1"/>

    <xsl:variable name="command">
      <xsl:choose>
        <xsl:when test="$nesting_level = 1">section</xsl:when>
        <xsl:when test="$nesting_level = 2">subsection</xsl:when>
        <xsl:when test="$nesting_level = 3">subsubsection</xsl:when>
        <xsl:when test="$nesting_level = 4">paragraph</xsl:when>
        <xsl:otherwise>subparagraph</xsl:otherwise>
      </xsl:choose>
    </xsl:variable>

    <!-- Sectioning command with the section title -->
    <xsl:text>&#10;\</xsl:text>
    <xsl:value-of select="$command"/>
    <xsl:text>{</xsl:text>
    <xsl:call-template name="tex">
      <xsl:with-param name="text" select="properties/*[@name=':Proteus-name']"/>
    </xsl:call-template>
    <xsl:text>}\ProteusLabel{</xsl:text>
    <xsl:value-of select="@id"/>
    <xsl:text>}&#10;</xsl:text>

    <!-- Apply templates to all children -->
    <xsl:apply-templates select="children/object">
      <xsl:with-param name="nesting_level" select="$nesting_level + 1"/>
    </xsl:apply-templates>
  </xsl:template>

</xsl:stylesheet>
